GET http://localhost:8080/

###

GET http://localhost:8080/

###

POST http://localhost:8080/api/register
Content-Type: application/json

{
    "username": "john",
    "mail": "a@mail.com",
    "password": "Abc.1234",
    "password_confirmation": "Abc.1234"
}

###

POST http://localhost:8080/api/login
Content-Type: application/json

{
    "username": "John",
    "mail": "a@mail.com",
    "password": "Abc.1234"
}

###

https://api.brawlstars.com/v1/players/%23YCQLVQV
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImE3OGZhZmI5LTQ3N2QtNGQ0MC05OTdkLTFlMjcxMmI0ZjIxMyIsImlhdCI6MTcxMjA2NjA5OSwic3ViIjoiZGV2ZWxvcGVyL2FhZGU3NjBhLWM4OTgtZDc5OC0yZDU1LTg2NjlmN2Q3NjY2MyIsInNjb3BlcyI6WyJicmF3bHN0YXJzIl0sImxpbWl0cyI6W3sidGllciI6ImRldmVsb3Blci9zaWx2ZXIiLCJ0eXBlIjoidGhyb3R0bGluZyJ9LHsiY2lkcnMiOlsiODAuMjguMTIxLjk3Il0sInR5cGUiOiJjbGllbnQifV19.A1PNSUgAaaQ2_9CWWjIErmXJv_uBjICk-EUVxUjq6k1laGXXJLV8dHM2L0ZTacr4j32A05dP1bXefc39PLYQ3A