GET http://localhost:8080/

###

GET http://localhost:8080/

###

POST http://localhost:8080/api/register
Content-Type: application/json

{
    "username": "john",
    "mail": "a@mail.com",
    "password": "Abc.1234",
    "password_confirmation": "Abc.1234"
}

###

POST http://localhost:8080/api/login
Content-Type: application/json

{
    "username": "John",
    "mail": "a@mail.com",
    "password": "Abc.1234"
}

###

// LOL testing

POST http://localhost:8080/api/getLolUserData/OSCDRY